### ISSUE TITLE
Semantic version implementation

### ISSUE THREAD

**Issue by rakateja** [securitybunker/databunker#21]
Hi Yuli. Thanks for the great project.

To avoid bugs happen in our application that due to new code or new release of databunker. Could you please implement semantic version for each release instead of always use latest? To make it simpler, I think we can use the pseudo-version number style, i.e
```
v1.1.0-20191109021931-daa7c04131f5 
```
Ref: https://go.dev/ref/mod#pseudo-versions
it has three parts
- base version prefix (i.e v1.1.0)
- timestamp (i.e 20191109021931)
- commit hash (i.e daa7c04131f5)

To make it simpler we can alway use the same base version prefix for each version.

How do you think? Thank you.

**Comment by stremovsky** [comment]
Hello

Thank you for brining this issue.

I implemented a simplified way of versioning for Databunker.

During the code build and container build process, the version is taken from this file:

https://github.com/securitybunker/databunker/blob/master/version.txt

Let me know if this is ok,

Otherwise let's have a chat to understand your requirements.

Yuli

**Comment by stremovsky** [comment]
I made another changes in build.sh script to generate version as you suggested.

Check now.

Best regards
