### ISSUE TITLE
ValidateNewApp limits tables created

### ISSUE THREAD

**Issue by jpadilla06** [securitybunker/databunker#6]
Given the line here, https://github.com/securitybunker/databunker/blob/master/src/userapps_api.go#L28 with implementation here: https://github.com/securitybunker/databunker/blob/bd6af1443b35445fc5a7a0c4f4f4c6837c7f020f/src/storage/mysql-storage.go#L871

Does databunker limit the number of tables that can be created for users given the hardcoded 100 for SQL and 10 for SQLite? We seem to be encountering the 405 db limitation error after a while which gets fixed when databunker is re-upped. Can we get clarity on the purpose of the limit? Thank you!

**Comment by stremovsky** [comment]
Hi,

There is no real need for this limitation.

I will remove it and publish an updated version later today.

**Comment by stremovsky** [comment]
I fixed the code and updated the docker containers.

https://github.com/securitybunker/databunker/commit/bdd7a28b66f1134e53837639b7cd0d36ae2b015f

**Comment by stremovsky** [comment]
I created a new patch to support multiple apps in 1 table.
https://github.com/securitybunker/databunker/commit/4876cfe8aa436f356e909318ffe20b87e003cb42

The `generic.use_separate_app_tables` variable can be configured to use multiple tables (the old way) or use only 1 table for all apps (the default new way).

This patch was done in order to remove the requirement to have higher database permissions.
Those permissions were required to create additional application tables.

**Comment by stremovsky** [comment]
Closing this
